export const PORT = 3000
export const DATABASE='mongodb+srv://*username*:*password*@*database*.scx6j.mongodb.net/'

export const WEB_CACHE=false
export const MAX_JSON_SIZE="10MB"
export const URL_ENCODE=true

export const REQUEST_LIMIT_TIME=20*60*1000
export const REQUEST_NUMBER=2000

export const RSS_FEEDS = [
    'https://rss.cnn.com/rss/cnn_topstories.rss',
    'https://feeds.bbci.co.uk/news/rss.xml',
    'https://rss.nytimes.com/services/xml/rss/nyt/World.xml',
    'https://news.ycombinator.com/rss'
]

export const SCHEDULED_INTERVAL= '0 * * * *'
export const KEYWORDS= {
    "Countries": [
        "United States",
        "Canada",
        "Mexico",
        "Brazil",
        "Argentina",
        "Chile",
        "Colombia",
        "Peru",
        "Venezuela",
        "Cuba",
        "Germany",
        "France",
        "Italy",
        "Spain",
        "Portugal",
        "United Kingdom",
        "Ireland",
        "Belgium",
        "Netherlands",
        "Luxembourg",
        "Sweden",
        "Norway",
        "Finland",
        "Denmark",
        "Iceland",
        "Switzerland",
        "Austria",
        "Greece",
        "Turkey",
        "Russia",
        "Ukraine",
        "Poland",
        "Czech Republic",
        "Hungary",
        "Romania",
        "Bulgaria",
        "Serbia",
        "Croatia",
        "Slovakia",
        "Slovenia",
        "Lithuania",
        "Latvia",
        "Estonia",
        "Bosnia and Herzegovina",
        "Montenegro",
        "Macedonia",
        "Albania",
        "Austria",
        "Singapore",
        "Malaysia",
        "Indonesia",
        "Philippines",
        "Thailand",
        "Vietnam",
        "Myanmar",
        "Cambodia",
        "Laos",
        "Brunei",
        "South Korea",
        "North Korea",
        "Japan",
        "Mongolia",
        "China",
        "India",
        "Pakistan",
        "Bangladesh",
        "Sri Lanka",
        "Nepal",
        "Bhutan",
        "Maldives",
        "Afghanistan",
        "Kazakhstan",
        "Uzbekistan",
        "Turkmenistan",
        "Kyrgyzstan",
        "Tajikistan",
        "Saudi Arabia",
        "United Arab Emirates",
        "Qatar",
        "Bahrain",
        "Oman",
        "Kuwait",
        "Israel",
        "Jordan",
        "Lebanon",
        "Syria",
        "Iraq",
        "Iran",
        "Egypt",
        "South Africa",
        "Nigeria",
        "Kenya",
        "Ethiopia",
        "Tanzania",
        "Uganda",
        "Ghana",
        "Ivory Coast",
        "Senegal",
        "Algeria",
        "Morocco",
        "Tunisia",
        "Zimbabwe",
        "Zambia",
        "Botswana",
        "Namibia",
        "Angola",
        "Mozambique",
        "Rwanda",
        "Burundi",
        "Cameroon",
        "Mali",
        "Niger",
        "Burkina Faso",
        "Togo",
        "Benin",
        "Sierra Leone",
        "Liberia",
        "Swaziland",
        "Lesotho",
        "Malawi",
        "Central African Republic",
        "Democratic Republic of the Congo",
        "Republic of the Congo",
        "Gabon",
        "Equatorial Guinea",
        "Sao Tome and Principe",
        "Djibouti",
        "Somalia",
        "Cape Verde",
        "Comoros",
        "Seychelles",
        "Palau",
        "Micronesia",
        "Marshall Islands",
        "Kiribati",
        "Tuvalu",
        "Nauru",
        "Solomon Islands",
        "Vanuatu",
        "Tonga",
        "Samoa",
        "Fiji",
        "Papua New Guinea",
        "New Zealand",
        "Australia",
        "Antarctica",
        "Saint Kitts and Nevis",
        "Antigua and Barbuda",
        "Dominica",
        "Saint Lucia",
        "Saint Vincent and the Grenadines",
        "Barbados",
        "Jamaica",
        "Bahamas",
        "Haiti",
        "Dominican Republic",
        "Puerto Rico",
        "Grenada",
        "Turks and Caicos Islands",
        "Cayman Islands",
        "British Virgin Islands",
        "U.S. Virgin Islands",
        "Anguilla"
    ],
    "People": [
        "Albert Einstein",
        "Isaac Newton",
        "Marie Curie",
        "Charles Darwin",
        "Pope Francis",
        "Galileo Galilei",
        "Nikola Tesla",
        "Leonardo da Vinci",
        "Stephen Hawking",
        "Jane Goodall",
        "Bill Gates",
        "Steve Jobs",
        "Mark Zuckerberg",
        "Elon Musk",
        "Jeff Bezos",
        "Oprah Winfrey",
        "Ruth Bader Ginsburg",
        "Malala Yousafzai",
        "Nelson Mandela",
        "Martin Luther King Jr.",
        "Mahatma Gandhi",
        "Winston Churchill",
        "John F. Kennedy",
        "Franklin D. Roosevelt",
        "Barack Obama",
        "Angela Merkel",
        "Margaret Thatcher",
        "Theresa May",
        "Emmanuel Macron",
        "Vladimir Putin",
        "Xi Jinping",
        "Justin Trudeau",
        "Pope Francis",
        "Mother Teresa",
        "Dalai Lama",
        "Aung San Suu Kyi",
        "Desmond Tutu",
        "Angela Davis",
        "Amelia Earhart",
        "Florence Nightingale",
        "Virginia Woolf",
        "Harriet Tubman",
        "Frida Kahlo",
        "Rosa Parks",
        "Coco Chanel",
        "Maya Angelou",
        "Toni Morrison",
        "Simone de Beauvoir",
        "Stephen King",
        "J.K. Rowling",
        "Agatha Christie",
        "Ernest Hemingway",
        "F. Scott Fitzgerald",
        "George Orwell",
        "Jane Austen",
        "Mark Twain",
        "Charles Dickens",
        "Leo Tolstoy",
        "Fyodor Dostoevsky",
        "Gabriel Garcia Marquez",
        "Pablo Neruda",
        "Rumi",
        "Lao Tzu",
        "Socrates",
        "Plato",
        "Aristotle",
        "Confucius",
        "Sun Tzu",
        "Niccolo Machiavelli",
        "Thomas Hobbes",
        "John Locke",
        "Jean-Jacques Rousseau",
        "Karl Marx",
        "Friedrich Engels",
        "John Stuart Mill",
        "Hannah Arendt",
        "Simone de Beauvoir",
        "Michael Foucault",
        "Jacques Derrida",
        "Jürgen Habermas",
        "Noam Chomsky",
        "Richard Dawkins",
        "Daniel Dennett",
        "David Chalmers",
        "Kurt Gödel",
        "Alan Turing",
        "Ada Lovelace",
        "Grace Hopper",
        "Tim Berners-Lee",
        "Linus Torvalds",
        "Larry Page",
        "Sergey Brin",
        "Larry Ellison",
        "Bill Gates",
        "Steve Wozniak",
        "Howard Schultz",
        "Richard Branson",
        "Walt Disney",
        "George Lucas",
        "Steven Spielberg",
        "Martin Scorsese",
        "Alfred Hitchcock",
        "Quentin Tarantino",
        "Christopher Nolan",
        "Meryl Streep",
        "Robert De Niro",
        "Audrey Hepburn",
        "Denzel Washington",
        "Leonardo DiCaprio",
        "Tom Hanks",
        "Harrison Ford",
        "Natalie Portman",
        "Scarlett Johansson",
        "Beyoncé",
        "Madonna",
        "Whitney Houston",
        "Elvis Presley",
        "Michael Jackson",
        "Prince",
        "Bob Marley",
        "Freddie Mercury",
        "John Lennon",
        "Paul McCartney",
        "Ringo Starr",
        "George Harrison",
        "David Bowie",
        "Kurt Cobain",
        "Lady Gaga",
        "Taylor Swift",
        "Adele",
        "Ed Sheeran",
        "Bruno Mars",
        "Katy Perry",
        "Billie Eilish",
        "Selena Gomez",
        "Justin Bieber",
        "Demi Lovato",
        "Miley Cyrus",
        "Rihanna"
    ],
    "Events": [
        "World War I",
        "World War II",
        "Cold War",
        "American Civil War",
        "French Revolution",
        "Industrial Revolution",
        "Great Depression",
        "Civil Rights Movement",
        "Women's Suffrage Movement",
        "Fall of the Berlin Wall",
        "September 11 Attacks",
        "Moon Landing",
        "Vietnam War",
        "Korean War",
        "Gulf War",
        "War in Afghanistan",
        "War in Iraq",
        "Arab Spring",
        "Brexit Vote",
        "COVID-19 Pandemic",
        "Olympics",
        "FIFA World Cup",
        "Super Bowl",
        "Grammy Awards",
        "Academy Awards",
        "World Series",
        "Nobel Prize",
        "Earth Day",
        "International Women's Day",
        "World Health Day",
        "World Environment Day",
        "International Day of Peace",
        "Human Rights Day",
        "International Workers' Day",
        "Black History Month",
        "Pride Month",
        "National Indigenous Peoples Day",
        "Thanksgiving",
        "Christmas",
        "Hanukkah",
        "Diwali",
        "Eid al-Fitr",
        "Ramadan",
        "Lunar New Year",
        "Holi",
        "Midsummer",
        "Oktoberfest",
        "Carnival",
        "Day of the Dead",
        "Chinese New Year",
        "Rosh Hashanah",
        "Yom Kippur",
        "Lent",
        "Ash Wednesday",
        "Good Friday",
        "Easter",
        "Valentine's Day",
        "Father's Day",
        "Mother's Day",
        "International Men's Day",
        "World Mental Health Day",
        "World Refugee Day",
        "International Day of Education",
        "International Day of Happiness",
        "World Population Day",
        "World Food Day",
        "International Day of Charity",
        "World Oceans Day",
        "World Soil Day",
        "World Tourism Day",
        "International Volunteer Day",
        "International Nurses Day",
        "World Teachers' Day",
        "International Day of Families",
        "World Youth Skills Day",
        "International Literacy Day",
        "World AIDS Day",
        "World Cancer Day",
        "World Diabetes Day",
        "International Day Against Drug Abuse",
        "World Day Against Child Labor",
        "World Telecommunication Day",
        "World Post Day",
        "World Radio Day"
    ],
    "Places": [
        "New York City",
        "Los Angeles",
        "Chicago",
        "Houston",
        "Phoenix",
        "Philadelphia",
        "San Antonio",
        "San Diego",
        "Dallas",
        "San Jose",
        "Austin",
        "Jacksonville",
        "Fort Worth",
        "Columbus",
        "Charlotte",
        "San Francisco",
        "Indianapolis",
        "Seattle",
        "Denver",
        "Washington, D.C.",
        "Boston",
        "El Paso",
        "Nashville",
        "Detroit",
        "Oklahoma City",
        "Portland",
        "Las Vegas",
        "Milwaukee",
        "Baltimore",
        "Albuquerque",
        "Tucson",
        "Fresno",
        "Sacramento",
        "Long Beach",
        "Kansas City",
        "Mesa",
        "Virginia Beach",
        "Atlanta",
        "Colorado Springs",
        "Omaha",
        "Raleigh",
        "Miami",
        "Cleveland",
        "Tulsa",
        "Oakland",
        "Minneapolis",
        "Wichita",
        "New Orleans",
        "Arlington",
        "Bakersfield",
        "Tampa",
        "Honolulu",
        "Anaheim",
        "Aurora",
        "Santa Ana",
        "Corpus Christi",
        "Riverside",
        "St. Louis",
        "Pittsburgh",
        "Lexington",
        "Anchorage",
        "Stockton",
        "Cincinnati",
        "Saint Paul",
        "Toledo",
        "Greensboro",
        "Henderson",
        "Plano",
        "Newark",
        "Chula Vista",
        "Baton Rouge",
        "Jersey City",
        "Chandler",
        "Fort Wayne",
        "Buffalo",
        "Durham",
        "St. Petersburg",
        "Irvine",
        "Laredo",
        "Lubbock",
        "Madison",
        "Gilbert",
        "Scottsdale",
        "Glendale",
        "Mobile",
        "Salt Lake City",
        "Grand Rapids",
        "Hialeah",
        "Tallahassee",
        "Moreno Valley",
        "Virginia Beach",
        "Cape Coral",
        "Antioch",
        "Overland Park",
        "Little Rock",
        "Tempe",
        "Columbia",
        "Amarillo",
        "Akron",
        "Augusta",
        "Mobile",
        "Grand Prairie",
        "Mesa",
        "Richmond",
        "Arlington",
        "Salt Lake City",
        "Baton Rouge",
        "Santa Ana",
        "Chattanooga"
    ],
    "Organizations": [
        "United Nations",
        "World Health Organization",
        "NATO",
        "European Union",
        "World Bank",
        "International Monetary Fund",
        "Amnesty International",
        "Greenpeace",
        "Red Cross",
        "Doctors Without Borders",
        "Oxfam",
        "Human Rights Watch",
        "UNICEF",
        "National Geographic",
        "World Wildlife Fund",
        "International Committee of the Red Cross",
        "Save the Children",
        "PETA",
        "Rotary International",
        "Habitat for Humanity",
        "Teach For All",
        "Bill & Melinda Gates Foundation",
        "Ford Foundation",
        "Rockefeller Foundation",
        "Clinton Foundation",
        "Open Society Foundations",
        "Mozilla Foundation",
        "Electronic Frontier Foundation",
        "Institute for Policy Studies",
        "Brookings Institution",
        "Carnegie Endowment for International Peace",
        "Cato Institute",
        "Heritage Foundation",
        "Rand Corporation",
        "American Civil Liberties Union",
        "National Association for the Advancement of Colored People",
        "Sierra Club",
        "Earthjustice",
        "League of Women Voters",
        "National Wildlife Federation",
        "American Heart Association",
        "American Cancer Society",
        "March of Dimes",
        "United Way",
        "Feeding America",
        "St. Jude Children's Research Hospital",
        "Big Brothers Big Sisters",
        "Special Olympics",
        "Boys & Girls Clubs of America",
        "YMCA",
        "Habitat for Humanity",
        "Junior Achievement",
        "Make-A-Wish Foundation",
        "Covenant House",
        "Teach For America",
        "Khan Academy",
        "Coursera",
        "edX",
        "LinkedIn Learning",
        "Udemy",
        "Skillshare",
        "FutureLearn",
        "Codecademy",
        "Pluralsight",
        "Nature Conservancy",
        "Audubon Society",
        "World Resources Institute",
        "National Park Service",
        "Centers for Disease Control and Prevention",
        "Food and Drug Administration",
        "National Institutes of Health",
        "Environmental Protection Agency",
        "NASA",
        "Federal Bureau of Investigation",
        "Central Intelligence Agency",
        "United States Agency for International Development",
        "National Security Agency",
        "National Aeronautics and Space Administration"
    ],
    "Concepts": [
        "Freedom",
        "Democracy",
        "Justice",
        "Equality",
        "Liberty",
        "Sustainability",
        "Peace",
        "Human Rights",
        "Social Justice",
        "Civic Engagement",
        "Community Service",
        "Philanthropy",
        "Education",
        "Innovation",
        "Technology",
        "Globalization",
        "Diversity",
        "Inclusion",
        "Cultural Competence",
        "Empathy",
        "Collaboration",
        "Interdependence",
        "Resilience",
        "Self-determination",
        "Environmentalism",
        "Capitalism",
        "Socialism",
        "Communism",
        "Feminism",
        "Civil Rights",
        "Animal Rights",
        "Corporate Social Responsibility",
        "Sustainable Development Goals",
        "Digital Literacy",
        "Critical Thinking",
        "Emotional Intelligence",
        "Conflict Resolution",
        "Media Literacy",
        "Health and Wellness",
        "Mindfulness",
        "Global Citizenship",
        "Social Entrepreneurship",
        "Active Citizenship",
        "Service Learning",
        "Green Technology",
        "Circular Economy",
        "Climate Change",
        "Ecosystem Restoration",
        "Biodiversity",
        "Conservation",
        "Humanitarianism",
        "Ethics",
        "Philosophy",
        "Psychology",
        "Sociology",
        "Economics",
        "Political Science",
        "Cognitive Science",
        "Artificial Intelligence",
        "Machine Learning",
        "Blockchain",
        "Cryptocurrency",
        "E-commerce",
        "Digital Marketing",
        "Data Science",
        "Big Data",
        "Cloud Computing",
        "Cybersecurity",
        "User Experience",
        "Design Thinking",
        "Agile Methodology",
        "Scrum",
        "Lean Startup",
        "Mind Mapping",
        "Time Management",
        "Goal Setting"
    ]
}


